[colors]
[colors.primary]
background = '#1E1E1E'
foreground = '#ffffff'

[colors.cursor]
text = "#1d1f21"
cursor = "#c5c8c6"

[colors.selection]
text = "#c5c8c6"
background = "#373b41"

[colors.normal]
black = "#000000"
red = "#cc6666"
green = "#b5bd68"
yellow = "#f0c674"
blue = "#81a2be"
magenta = "#b294bb"
cyan = "#8abeb7"
white = "#ffffff"

# Bright colors
[colors.bright]
black = '#444b6a'
red = '#ff7a93'
green = '#b9f27c'
yellow = '#ff9e64'
blue = '#7da6ff'
magenta = '#bb9af7'
cyan = '#0db9d7'
white = '#acb0d0'